export interface FAQ {
  id: number;
  question: string;
  answer: string;
}

export const faqs: FAQ[] = [
  {
    id: 1,
    question: "How does MyDocMaker work?",
    answer: "MyDocMaker uses advanced artificial intelligence to generate professional documents based on your prompts. Simply describe what you need, and our AI will create a complete document with proper formatting, structure, and content tailored to your requirements."
  },
  {
    id: 2,
    question: "What types of documents can I create?",
    answer: "You can create a wide variety of documents including business reports, presentations, research papers, blog posts, marketing materials, legal documents, resumes, and much more. Our AI is trained on diverse document types to meet your specific needs."
  },
  {
    id: 3,
    question: "Is my data secure and private?",
    answer: "Absolutely. We take data security seriously. All documents are encrypted in transit and at rest. We never share your content with third parties, and you maintain full ownership of everything you create. You can also delete your documents at any time."
  },
  {
    id: 4,
    question: "Can I collaborate with my team?",
    answer: "Yes! MyDocMaker includes real-time collaboration features. You can invite team members to edit documents together, leave comments, and track changes. Everyone stays in sync with automatic updates."
  },
  {
    id: 5,
    question: "What formats can I export to?",
    answer: "You can export your documents in multiple formats including PDF, DOCX (Microsoft Word), PPTX (PowerPoint), TXT, and Markdown. This ensures compatibility with any workflow or platform you're using."
  },
  {
    id: 6,
    question: "Do you offer a free trial?",
    answer: "Yes! We offer a free plan that allows you to create up to 5 documents per month. This is perfect for trying out the platform and seeing how it can benefit your workflow. Upgrade anytime to unlock unlimited documents and advanced features."
  },
  {
    id: 7,
    question: "Can I customize the AI-generated content?",
    answer: "Absolutely. Every document generated by our AI can be fully edited and customized. You have complete control over the content, formatting, and styling. Think of it as having an AI assistant that creates the first draft, which you can then refine to perfection."
  },
  {
    id: 8,
    question: "How accurate is the AI content?",
    answer: "Our AI is highly accurate and produces professional-quality content. However, we always recommend reviewing and editing the output to ensure it meets your specific requirements and includes any specialized information or context unique to your situation."
  }
];
